@base_backend_url = http://127.0.0.1:8000
@course_id =df1c36f2-4221-4307-a488-bfad5a0af489
@course_code=ece410h1

GET {{base_backend_url}}/courses/{{course_id}}
###

GET {{base_backend_url}}/reviews/course/{{course_id}}
###

POST {{base_backend_url}}/reviews
Content-Type: application/json

{
    "rating": 5,
    "courseId": "df1c36f2-4221-4307-a488-bfad5a0af489"
}

### Get Friend Requests
POST {{base_backend_url}}/friends/requests/get
Content-Type: application/json

{
    "userEmail": "navidkpour@gmail.com"
}

### Send Friend Request
POST {{base_backend_url}}/friends/requests
Content-Type: application/json

{
    "originEmail": "navidkpour@gmail.com",
    "destEmail": "nacojoe@gmail.com"
}

### Accept/Reject Friend Request
POST {{base_backend_url}}/friends/requests/response
Content-Type: application/json

{
    "accept": 0,
    "userEmail": "navidkpour@gmail.com",
    "friendRequestId": "3b1f7221-96ae-447b-af1b-1f6663d56202"
}

### Get Friends
POST {{base_backend_url}}/friends/get
Content-Type: application/json

{
    "userEmail": "navidkpour@gmail.com",
}


### Register User
POST {{base_backend_url}}/users
Content-Type: application/json

{
    "email": "navidkpour@gmail.com"
}