@base_backend_url = http://127.0.0.1:8000
@course_id =df1c36f2-4221-4307-a488-bfad5a0af489
@course_code=ece410h1

GET {{base_backend_url}}/courses/{{course_id}}
###

GET {{base_backend_url}}/reviews/course/{{course_id}}
###

POST {{base_backend_url}}/reviews
Content-Type: application/json

{
    "rating": 5,
    "courseId": "df1c36f2-4221-4307-a488-bfad5a0af489"
}